// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'employee_settings.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

EmployeeSettings _$EmployeeSettingsFromJson(Map<String, dynamic> json) =>
    EmployeeSettings(
      json['"file'] as String?,
      json['"fyMonth'] as String?,
      json['"fy_date'] as String?,
      json['"currency'] as String?,
      json['"otp_flag'] as bool?,
      json['"dial_code'] as String?,
      json['"time_zone'] as String?,
      json['"image_name'] as String?,
      json['"welcome_msg'] as String?,
      json['"company_name'] as String?,
      json['"country_code'] as String?,
      json['"gps_accuracy'] as String?,
      json['"is_gps_check'] as bool?,
      json['"branding_color'] as String?,
      json['"is_otp_allowed'] as bool?,
      json['"max_cart_value'] as int?,
      json['"min_cart_value'] as int?,
      json['"near_by_radius'] as int?,
      json['"onboard_action'] as int?,
      json['"time_zone_name'] as String?,
      json['"currency_symbol'] as String?,
      json['"onboard_process'] as int?,
      json['"attendance_query'] as String?,
      json['"beat_edit_action'] as int?,
      json['"geo_fence_radius'] as String?,
      json['"onboard_otp_flag'] as bool?,
      json['"beat_edit_process'] as int?,
      json['"allow_multiple_beats'] as bool?,
      json['"near_by_stores_limit'] as int?,
      json['"no_order_reason_flag'] as bool?,
      json['"salesman_hotline_msg'] as String?,
      json['"contact_number_length'] as int?,
      json['"near_by_stores_radius'] as int?,
      json['"order_confirmation_msg'] as String?,
      json['"default_distributor_role'] as int?,
      json['"default_distributor_group'] as int?,
      json['"onboard_alternate_otp_flag'] as bool?,
      json['"distributor_selection_confirmation'] as bool?,
    );

Map<String, dynamic> _$EmployeeSettingsToJson(EmployeeSettings instance) =>
    <String, dynamic>{
      '"file': instance.file,
      '"fyMonth': instance.fyMonth,
      '"fy_date': instance.fyDate,
      '"currency': instance.currency,
      '"otp_flag': instance.otpFlag,
      '"dial_code': instance.dialCode,
      '"time_zone': instance.timeZone,
      '"image_name': instance.imageName,
      '"welcome_msg': instance.welcomeMsg,
      '"company_name': instance.companyName,
      '"country_code': instance.countryCode,
      '"gps_accuracy': instance.gpsAccuracy,
      '"is_gps_check': instance.isGpsCheck,
      '"branding_color': instance.brandingColor,
      '"is_otp_allowed': instance.isOtpAllowed,
      '"max_cart_value': instance.maxCartValue,
      '"min_cart_value': instance.minCartValue,
      '"near_by_radius': instance.nearByRadius,
      '"onboard_action': instance.onboardAction,
      '"time_zone_name': instance.timeZoneName,
      '"currency_symbol': instance.currencySymbol,
      '"onboard_process': instance.onboardProcess,
      '"attendance_query': instance.attendanceQuery,
      '"beat_edit_action': instance.beatEditAction,
      '"geo_fence_radius': instance.geoFenceRadius,
      '"onboard_otp_flag': instance.onboardOtpFlag,
      '"beat_edit_process': instance.beatEditProcess,
      '"allow_multiple_beats': instance.allowMultipleBeats,
      '"near_by_stores_limit': instance.nearByStoresLimit,
      '"no_order_reason_flag': instance.noOrderReasonFlag,
      '"salesman_hotline_msg': instance.salesmanHotlineMsg,
      '"contact_number_length': instance.contactNumberLength,
      '"near_by_stores_radius': instance.nearByStoresRadius,
      '"onboard_alternate_otp_flag': instance.onboardAlternateOtpFlag,
      '"order_confirmation_msg': instance.orderConfirmationMsg,
      '"default_distributor_role': instance.defaultDistributorRole,
      '"default_distributor_group': instance.defaultDistributorGroup,
      '"distributor_selection_confirmation':
          instance.distributorSelectionConfirmation,
    };
